# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
# safe: true
markdown_ext: md

##############################################################################

# Site settings

name: Register-Annotation-Docs
baseurl: "/register-annotation-docs"
homeurl: "https://github.com/TurkuNLP/register-annotation-docs/"
editurl: "https://github.com/TurkuNLP/register-annotation-docs/edit/gh-pages"
issueurl: "https://github.com/TurkuNLP/register-annotation-docs/issues"

##############################################################################

# Collection settings

collections:
  register:
    output: true
